title: Olivier Dolbeau
url: https://odolbeau.fr
description: |
  Hello. My name is Olivier Dolbeau (@odolbeau).
  I currently live in France and work as a freelancer!

author:
    name: Olivier Dolbeau
    email: contact@odolbeau.fr
    twitter: odolbeau
    github: odolbeau
    stackoverflow: 1080352/olivier-dolbeau
