title: Olivier Dolbeau
url: https://odolbeau.fr
description: |
  Hello. My name is Olivielr Dolbeau (@odolbeau).
  I currently live in Paris and work as a web architect at BlaBlaCar.

author:
    name: Olivier Dolbeau
    email: contact@odolbeau.fr
    twitter: odolbeau
    github: odolbeau
    stackoverflow: 1080352/olivier-dolbeau
